title: BotanyBase Docs
description: BotanyBase Docs
remote-theme: "just-the-docs"

url: https://botanybase.github.io/docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
